"""
Django settings for withings_server project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
import sys
import zoneinfo
import tzlocal
from pathlib import Path

def read_from_file(filepath):
    if os.path.exists(filepath):
        try:
            with open(filepath, 'r') as file:
                file_content = file.read()
                print("read from " + filepath)
                return file_content.strip()
        except FileNotFoundError:
            print(f"Error: File not found: {filepath}")
            return None
        except Exception as e:
            print(f"An error occurred: {e}")
            return None
    else:
        return None
    
def get_docker_secret(filename):
    filepath = os.path.join('/run/secrets', filename)
    return read_from_file(filepath)

def get_local_file(filename):
    filepath = os.path.join('./', filename)
    return read_from_file(filepath)

def get_env_var(varname):
    value = os.environ.get(varname)
    if value:
        print("read from environment variable")
        return os.environ.get(varname)
    return ""

def get_setting(setting, default = ""):
    print(setting + " ", end="")
    setting_funcs = [get_env_var, get_local_file, get_docker_secret]
    for func in setting_funcs:
        result = func(setting)
        if result:
            return result
    if default:
        print ("not found, using default value '" + default + "'")
        return default
    else:
        print("not found, no default available")
        return ""


# THESE SETTINGS NOW COME FROM ENVIRONMENT VARIABLES
WITHINGS_DEBUG = get_setting("WITHINGS_DEBUG", "False")
WITHINGS_HOSTNAME = get_setting("WITHINGS_HOSTNAME", "localhost")
WITHINGS_CONTEXT_ROOT = get_setting("WITHINGS_CONTEXT_ROOT", "withings")
context_root_trailing_slash = WITHINGS_CONTEXT_ROOT + "/" if WITHINGS_CONTEXT_ROOT else ""
WITHINGS_REDIRECT_URI = get_setting("WITHINGS_REDIRECT_URI", 'https://' + WITHINGS_HOSTNAME + '/' + context_root_trailing_slash + 'callback/')
WITHINGS_CLIENT_ID = get_setting("WITHINGS_CLIENT_ID")
WITHINGS_CLIENT_SECRET = get_setting("WITHINGS_CLIENT_SECRET")
WITHINGS_DJANGO_SECURE_KEY = get_setting("WITHINGS_DJANGO_SECURE_KEY", "django-insecure-please-consider-supplying-a-secure-key-23^%36n4Gdf")
WITHINGS_TIME_ZONE = get_setting("WITHINGS_TIME_ZONE", tzlocal.get_localzone_name())

if not WITHINGS_HOSTNAME:
    print("Unable to determine WITHINGS_HOSTNAME, exiting")
    sys.exit()

debug_check = WITHINGS_DEBUG.lower() if WITHINGS_DEBUG else False
DEBUG = debug_check == "true" or debug_check == "1" or debug_check == "y"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-please-consider-supplying-a-secure-key-23^%36n4Gdf"

# Used if deploying to a path, i.e. https://www.example.com/withings would be 'withings'

# Allow https proxy headers
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow hosts, including proxy hosts
ALLOWED_HOSTS = ['127.0.0.1', 'localhost', WITHINGS_HOSTNAME]

CSRF_TRUSTED_ORIGINS = ['https://' + WITHINGS_HOSTNAME, 'http://' + WITHINGS_HOSTNAME + ':8000', 'http://127.0.0.1:8000']
CSRF_COOKIE_DOMAIN = WITHINGS_HOSTNAME
CSRF_COOKIE_PATH = '/' + WITHINGS_CONTEXT_ROOT

SECURE_REFERRER_POLICY = "same-origin"

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "accounts.apps.AccountsConfig",
    "withings.apps.WithingsConfig",
]

AUTH_USER_MODEL = "accounts.CustomUser" # User CustomUser for authentication

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    #"django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "withings_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "withings_server.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db/db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

USE_I18N = True

USE_TZ = True

TIME_ZONE = WITHINGS_TIME_ZONE

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = context_root_trailing_slash + "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOCAL_WITHINGS_DATA_DIR = 'files'
WORKING_WITHINGS_DATA_PATH = os.path.join(BASE_DIR, LOCAL_WITHINGS_DATA_DIR)

